import { type NextPage } from "next";
import Head from "next/head";
import { SignInButton, useUser, SignOutButton } from "@clerk/nextjs";
import { api } from "~/utils/api";


const Home: NextPage = () => {

  const user = useUser()

  const { data } = api.posts.getAll.useQuery()

  return (
    <>
      <Head>
        <title>Chirp</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-[#121212]">
      {
        !user.isSignedIn  &&  <SignInButton>
                                <button className="text-white">Sign in</button>
                              </SignInButton>
      }
      {
        !!user.isSignedIn &&  <SignOutButton>
                                <button className="text-white">Sign out</button>
                              </SignOutButton>
      }

      {
        data?.map((post) => {
          console.log(post.content)
          return (
            <div key={post.id} className="text-white">{post.content}</div>
          )
        }) 
      }

      </main>
    </>
  );
};

export default Home;
